### ISSUE TITLE
findOne throws exception instead of returning null when resource not found

### ISSUE THREAD

**Issue by edwingustafson** [Microsoft/azure-spring-boot-starters#141]
`findOne` should return `null` when no document is found with the given `id`. https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findOne-ID-

Instead it is throwing an exception:

```
java.lang.RuntimeException: findById exception
	at com.microsoft.azure.spring.data.documentdb.core.DocumentDbTemplate.findById(DocumentDbTemplate.java:117)
	at com.microsoft.azure.spring.data.documentdb.repository.support.SimpleDocumentDbRepository.findOne(SimpleDocumentDbRepository.java:64)
⋮
Caused by: com.microsoft.azure.documentdb.DocumentClientException: Message: {"Errors":["Resource Not Found"]}
```

**Comment by ZhijunZhao** [comment]
@edwingustafson Thank you for reporting this issue. We're working on a fix for it.
